<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nisa Rahmasari">
<meta name="dcterms.date" content="2024-01-20">

<title>Pengaruh Ekspor Lada Putih ke Negara Jepang Terhadap PDB Indonesia tahun 2013-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor Lada Putih ke Negara Jepang Terhadap PDB Indonesia tahun 2013-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nisa Rahmasari </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid" width="384"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Ekspor merupakan salah satu pilar utama dalam perekonomian suatu negara, memainkan peran penting dalam pertumbuhan ekonomi dan pembangunan nasional. Dalam konteks Indonesia, sektor ekspor telah menjadi sumber pendapatan yang signifikan dan berkontribusi secara substansial terhadap Produk Domestik Bruto (PDB). Salah satu komoditas ekspor unggulan yang telah memberikan kontribusi positif bagi perekonomian Indonesia adalah lada putih.</p>
<p>Lada putih, sebagai salah satu rempah-rempah berkualitas tinggi, memiliki permintaan yang stabil di pasar internasional. Negara Jepang, sebagai salah satu mitra dagang utama Indonesia, telah menjadi tujuan utama ekspor lada putih Indonesia selama beberapa tahun terakhir. Peningkatan ekspor lada putih ke Jepang dapat memberikan dampak signifikan terhadap pertumbuhan ekonomi Indonesia, khususnya pada tingkat Produk Domestik Bruto (PDB).</p>
<p>Melalui periode tahun 2013 hingga 2022, dinamika ekspor lada putih ke Jepang dipengaruhi oleh berbagai faktor, termasuk perubahan kebijakan perdagangan internasional, fluktuasi nilai tukar, dan perubahan pola konsumsi di pasar Jepang. Oleh karena itu, penting untuk memahami dan menganalisis dampak ekspor lada putih ke Jepang terhadap PDB Indonesia selama periode tersebut.</p>
<p>Penelitian ini bertujuan untuk menyelidiki dan menganalisis pengaruh ekspor lada putih ke Negara Jepang terhadap pertumbuhan Produk Domestik Bruto Indonesia dalam rentang waktu tahun 2013 hingga 2022. Dengan pemahaman yang lebih mendalam terhadap keterkaitan antara ekspor lada putih dan PDB, penelitian ini diharapkan dapat memberikan kontribusi positif bagi perumusan kebijakan perdagangan luar negeri Indonesia serta pengembangan strategi ekonomi yang berkelanjutan.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Ruang lingkup penelitian ini mencakup kajian mendalam terhadap dampak ekspor lada putih ke Negara Jepang terhadap pertumbuhan Produk Domestik Bruto (PDB) Indonesia selama periode tahun 2013 hingga 2022. Dalam memahami ruang lingkup penelitian ini, beberapa dimensi akan dijelaskan untuk memberikan gambaran komprehensif mengenai parameter dan variabel yang menjadi fokus analisis.</p>
<p>Dimana dalam pengambilan data ini mengambil 2 Variabel antara lain nilai ekspor Indonesia dan nilai Gross Domestic Product (GDP) Data yang digunakan adalah data yang bersifat time series yaitu dalam kurun waktu 2013-2022 dengan satuan USD untuk memudahkan penyetaraan mata uang secara internasional.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Apakah ekspor komoditi lada putih ke Jepang dapat berpengaruh terhadap GDP Indonesia?</li>
<li>Bagaimana hubungan ekspor terhadap GDP Indonesia?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan dari penelitian ini adalah untuk menilai sejauh mana nilai ekspor lada putih ke Jepang memengaruhi GDP Indonesia selama periode 2013-2022. Selain itu, untuk menentukan apakah ada korelasi positif antara ekspor dan pertumbuhan ekonomi. Manfaat yang diharapkan dari hasil penelitian ini adalah Memberikan wawasan kepada pembaca tentang sejauh mana kebijakan ekspor dapat menjadi penyebab bagi pertumbuhan ekonomi Indonesia.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Ini tidak wajib ada di tulisan anda tapi anda dapat menunjukkan Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readxl' was built under R version 4.3.2</code></pre>
</div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Perdagangan internasional adalah salah satu cara menghadapi perekonomian global dengan memanfaatkan kekayaan dari masing-masing negara (Rochmat et al., 2017).</p>
<p>Ekspor merupakan suatu komponen pengeluaran agregat, oleh sebab itu ekspor dapat mempengaruhi pendapatan nasional yang akan dicapai. Apabila ekspor bertambah, pengeluaran agregat bertambah tinggi dan selanjutnya akan menaikkan pendapatan nasional, akan tetapi sebaliknya pendapatan nasional tidak dapat mempengaruhi ekspor, ekspor belum tentu dapat mengalami perubahan walaupun pendapatan nasional tetap (Affandi,2018)</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut adalah data yang digunakan sebagai penelitian, data dibawah ini merupakan data ekspor lada putih ke Jepang, dan PDB Indonesia dengan satuan USD.</p>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Ekspor Lada Putih</th>
<th>PDB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>592,025</td>
<td>9,12524E+11</td>
</tr>
<tr class="even">
<td>2014</td>
<td>693,47</td>
<td>8,90815E+11</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>939,3924</td>
<td>8,60854E+11</td>
</tr>
<tr class="even">
<td>2016</td>
<td>978,7988</td>
<td>9,31877E+11</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>461,9</td>
<td>1,01562E+12</td>
</tr>
<tr class="even">
<td>2018</td>
<td>869,5</td>
<td>1,04227E+12</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>738,4</td>
<td>1,1191E+12</td>
</tr>
<tr class="even">
<td>2020</td>
<td>975,3</td>
<td>1,05905E+12</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>955,1</td>
<td>1,18651E+12</td>
</tr>
<tr class="even">
<td>2022</td>
<td>1020,5</td>
<td>1,3191E+12</td>
</tr>
</tbody>
</table>
<p>penelitian ini menggunakan data sekunder dengan bentuk time series 2013-2022, data yang dipakai diolah dan bersumber dari Badan Pusat Statistik.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Metopel'</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'UAS.xlsx'</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>dat)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>x,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"Ekspor Lada Putih ke Jepang"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh Error terhadap Ekspor Lada Putih ke Jepang</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>y,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"PDB"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot Pengaruh Error terhadap PDB</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini bermaksud mencari hubungan antara Ekspor lada putih ke Jepang dan PDB. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah PDB dan <span class="math inline">\(x_t\)</span> adalah Ekspor Lada Putih ke Jepang.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Variabel</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t value</th>
<th>Prob (.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>8.060e+11</td>
<td>2.104e+11</td>
<td>3.832</td>
<td>0.005</td>
</tr>
<tr class="even">
<td>X</td>
<td>2.769e+08</td>
<td>2.498e+08</td>
<td>1.109</td>
<td>0.300</td>
</tr>
<tr class="odd">
<td>R Squared</td>
<td>0.1331</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Adjusted R-squared</td>
<td>0.02479</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>F-statistic</td>
<td>1.229</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Prob(F-statistic)</td>
<td>0.2999</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Hasil regresi yang telah didapat dimasukan ke dalam rumus persamaan yang ada sehingga menjadi: <span class="math display">\[
Y= 8.060+2.769X
\]</span> Peran dari ekspor lada putih ke Jepang dalam pertumbuhan ekonomi berperan penting dalam meningkatkan PDB dikarenakan nilai variabel X yang menunjukkan positif, meskipun demikian, hasil regresi ini menunjukkan bahwa pengaruh nilai ekspor lada putih ke Jepang tidak sepenuhnya mempengaruhi GDP di indonesia.ada beberapa faktor lain yang menyebabkan peningkatan PDB Indonesia. dapat diasumsikan bahwa setiap kenaikan ekspor 1, maka GDP akan meningkat sebesar 2.769.</p>
<p>Nilai Adjusted R-squared sebesar 0.02479 menunjukan bahwa variabel independen di dalam penelitian dapat menjelaskan variasi variabel dependen sebesar 2,479 persen. F-statistic dengan nilai 1.229 menjelaskan bahwa variabel independen dalam jangka panjang seperti ekspor lada putih memiliki pengaruh signifikan terhadap pertumbuhan ekonomi atau GDP Indonesia.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Metopel'</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'UAS.xlsx'</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>dat)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = dat)

Residuals:
       Min         1Q     Median         3Q        Max 
-2.053e+11 -9.480e+10 -1.079e+10  1.019e+11  2.305e+11 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 8.060e+11  2.104e+11   3.832    0.005 **
x           2.769e+08  2.498e+08   1.109    0.300   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.429e+11 on 8 degrees of freedom
Multiple R-squared:  0.1331,    Adjusted R-squared:  0.02479 
F-statistic: 1.229 on 1 and 8 DF,  p-value: 0.2999</code></pre>
</div>
</div>
<p>dilihat dari tabel di atas menujukan ketika kenaikan ekspor lada putih ke Jepang dengan diasumsikan 1 nilainya, maka dapat meningkatkan PDB sebesar 2.769.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Setelah dilakukannya penelitian melalui regresi dapat disimpulkan antara lain:</p>
<p>Penelitian ini membahas dampak ekspor lada putih ke Negara Jepang terhadap Produk Domestik Bruto (PDB) Indonesia dalam periode 2013-2022. Hasil analisis regresi menunjukkan bahwa ekspor lada putih memegang peran penting dalam meningkatkan pertumbuhan ekonomi namun tidak sepenuhnya mempengaruhi, sebagaimana ditunjukkan oleh nilai variabel X yang menunjukkan korelasi positif.</p>
<p>Meskipun demikian, hasil regresi juga mengungkapkan bahwa pengaruh ekspor lada putih terhadap PDB Indonesia tidak bersifat eksklusif. Terdapat faktor-faktor lain yang turut menyumbang terhadap peningkatan PDB Indonesia, dan pengaruh variabel ekspor lada putih tidak sepenuhnya mempengaruhi GDP.</p>
<p>Dalam konteks ini, dapat diasumsikan bahwa setiap kenaikan satu unit ekspor lada putih mengakibatkan peningkatan sebesar 2.769 pada GDP Indonesia. Meskipun angka ini memberikan gambaran kontribusi positif, kesimpulan perlu diambil dengan berhati-hati, mengingat nilai Adjusted R-squared sebesar 0.02479. Angka ini menunjukkan bahwa variasi dalam PDB Indonesia hanya dapat dijelaskan sekitar 2,479 persen oleh variabel independen, yaitu ekspor lada putih ke Jepang.</p>
<p>Meski demikian, nilai F-statistic sebesar 1.229 menegaskan bahwa variabel independen, yakni ekspor lada putih, memiliki pengaruh signifikan dalam jangka panjang terhadap pertumbuhan ekonomi atau GDP Indonesia. Oleh karena itu, sementara ekspor lada putih ke Jepang memberikan kontribusi positif yang signifikan, penelitian lebih lanjut diperlukan untuk memahami dengan lebih mendalam faktor-faktor lain yang turut berperan dalam dinamika pertumbuhan ekonomi Indonesia selama periode penelitian.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Affandi, Zulham, T., &amp; Gunawan, E. (2018). Pengaruh Ekspor, Impor Dan Jumlah Penduduk. Jurnal Perspektif Ekonomi Darussalam, 4(2), 249–264. https://doi.org/https://doi.org/10.24815/jped.v4i2.13021</p>
<p>Trilarasati, L. S., Khafiya, N. N., Adriananta, M., Fitriana, A. N., &amp; Velma, M. G. (2023). Komparasi Daya Saing Ekspor Lada Indonesia Terhadap. Jurnal Economina, 2(1), 231–240.</p>
<p>Wardani, V. A. T., &amp; Sunyigono, A. K. (2002). DAYA SAING DAN FAKTOR YANG MEMPENGARUHI EKSPOR LADA INDONESIA KE INDIA. Jurnal Ekonomi Pertanian Dan Agribisnis (JEPA).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>